# This is a basic workflow to help you get started with Actions
name: SyncToS3
# Controls when the action will run. 
on: [ push, pull_request ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/s3-sync 
    steps:
      - uses: actions/checkout@master
      - name: Retrive JSON File
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "./.github/package.json"
      # - run: |
      #     echo 
      #     echo ${{steps.json_properties.outputs.version}}
      #     echo 
      - name: Set Upload folder var on S3 bucket
        run: echo "UPLOAD_FOLDER=${{steps.json_properties.outputs.product_category}}/${{steps.json_properties.outputs.name}}/${{steps.json_properties.outputs.version}}" >> $GITHUB_ENV
      - name: Zip the repo and Pack to S3_Upload folder before uploading
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: ./s3_upload/${{steps.json_properties.outputs.name}}.zip
      - name: Upload to S3 Folder
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          SOURCE_DIR: './s3_upload'
          DEST_DIR: '/$UPLOAD_FOLDER/'